spring:
  application:
    name: car-server
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cardb


server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/
